cafeteria/cafeteria/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('menu/', include('menu.urls')),
    path('admin/', admin.site.urls),
]

cafeteria/menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

cafeteria/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

cafeteria/menu/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    meal_sum = models.IntegerField(default=0)
    total_sum = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

cafeteria/menu/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question, Choice




# Display questins
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'menu/index.html', context)

# Get question and choices
def detail(request, question_id):
  try:
    question = Question.objects.get(pk=question_id)
  except Question.DoesNotExist:
    raise Http404("Question does not exist")
  return render(request, 'menu/detail.html', { 'question': question })

# Get question and display results
def results(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  return render(request, 'menu/results.html', { 'question': question })

# Submit for a question and choice
def vote(request, question_id):
    
    

    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        
        return render(request, 'menu/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        ## Increase choice(menu) and save to the database
        selected_choice.meal_sum += selected_choice.price
        selected_choice.total_sum += selected_choice.price
        selected_choice.votes += 1
        selected_choice.save()
        if selected_choice.total_sum > 500:
          print("Excellent! Lots of hungry students around today")
      
        return HttpResponseRedirect(reverse('menu:results', args=(question.id,)))

cafeteria/pages/views.py
from django.shortcuts import render

def index(request):
  return render(request, 'pages/index.html')

cafeteria/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"      
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <title>Welcome to Cafeteria {% block title %}{% endblock %}</title>
  </head>
  <body>
    
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <div class="container">
        <a class="navbar-brand" href="/">Cafeteria</a>
      </div>
    </nav>
    <div class="container" >
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
    
  </body>
</html>

cafeteria/templates/menu/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'menu:index' %}">Back To menu</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'menu:vote' question.id %}" method="post">
	{% csrf_token %} 
	{% for choice in question.choice_set.all %}
		<div class="form-check">
			<input
				type="radio"
				name="choice"
				class="form-check-input"
				id="choice{{ forloop.counter }}"
				value="{{ choice.id }}"
			/>
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
			>
		</div>
	{% endfor %}
	<input type="submit" value="Submit" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

cafeteria/templates/menu/index.html
{% extends 'base.html' %} 
{% block content %} 
  <h1 class="text-center mb-3">Lunch conversation</h1>
  {% if latest_question_list %}
    {% for question in latest_question_list %}
      <div class="card mb-3">
        <div class="card-body">
          <p class="lead">{{ question.question_text }}</p>
          <a href="{% url 'menu:detail' question.id %}" class="btn btn-primary btn-sm">View & Submit</a>
          <a href="{% url 'menu:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No menu available</p>
  {% endif %}
{% endblock %}

cafeteria/templates/menu/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		{{ choice.choice_text }}  <span class="badge badge-success float-right">{{ choice.votes }} dish {{ choice.votes | pluralize }}</span>
	</li>
	{% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'menu:index' %}">Back To menu</a>
<a class="btn btn-primary" href="{% url 'menu:detail' question.id %}">Try again?</a>
<div class="container">
<h3 class="mb-5 text-center"> Overview </h3>
<ul class="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		{{ choice.choice_text }} <span class="badge badge-danger float-right"> Meal sum : {{choice.total_sum}} </span>    <span class="badge badge-success float-right"> Total sum : {{choice.meal_sum}} </span>	
		
	</li>
	{% endfor %}
</ul>
</div>


{% endblock %}

cafeteria/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
<div class="card-body">

  <p>What would you like today? (choice 'how is business?' to attempt small talk, or 'not hungry' to stop)
  </p>

</div>
  
</div>

<div class="card text-center">
  <div class="card-body">   
    
    <a class="btn btn-secondary " href="#" id="not_hungry"  >
      Not hungry</a>
      <a class="btn btn-primary" href="{% url 'menu:index' %}">
        how is business?</a
        >
  </div>
  </div>
  
  
  <script>
    $(document).ready(function(){
      $('#not_hungry').on('click', function(){
        alert('Alright, Welcome back later!');
      });
    });
  </script>
{% endblock %}